language: node_js
node_js:
  - "6.1"
install:
  - "npm install"
script:
  - ./deploy.sh
env:
  global:
    - GITHUB_REPO: "open-curriculum/oerschema"
    - secure: "XELQn7lDenZS6rrY3f/7KuXHQSl+3ZgrCaEmOXOLAqqzW+59G0qdfgCa3u3+7Ap3od1PHeYnKzCWFAfICGDPpM32OHqFUoaDfWKtIkNBVjkp/Bm5JWfKo16+t2A4I0QwbJpl9fT3yTw8WJTE1vAWBm3lTh3hRzalJ7526Ppdi6pavf90Lkhf1VvsFUJX8YhDFXhVZoBHuewzy0FdJeSmEWkxlE4eXEdIAjfbr3bH7WJrqOsaueMVg95UyJyc/EuFsA/ZBTI3rvOkHnkFfsBja+u+jehOavzHM8hjfpDalT+0fnmTwPSMDP9MA9h3CStVz7zuOv3ZKGQKSJiAmaixkWhNbTmqWJwyb3WHgBICHqnvkcvs6DLYaUyioTTN86rlD/4/O7772issW1G7YSMxP4oTKw4RqXYn9+bDbEpBqJFOI3o+yGhEWCrIGNIvvEyKqDcdOy9y6BrjS9iambuySmdjqStw9vamB3r6pbS497WMkp5GpiBf6W5ZshYMKXW3JJLAhH/9VWuR2GANWO/VoktHj5qIe0RC0d6BtYHFKobwvdRTLxt7Ndh96MdyQ4ti+CmIsODBDw/oYi+v/ssbQONjWF1yqu9O2MDnu+Gdhuds0AoJhGSW47jAz6K1B3k88LYURS1lYxz1iAUbEa7LwdW6wz4c3EHEJ9zZWpzemtE="
branches:
  only:
    - "master"