# All classes and properties are also subClasses of themselves
# All classes have the rdfs:type of rdfs:Class
classes:
  Thing:
    comment: "The most generic type of item"
    path: "Thing"
    baseVocab: "http://schema.org/"
    properties:
      - "name"
      - "additionalType"
      - "description"
      - "image"
      - "mainEntityOfPage"

  Intangible:
    path: "Thing/Intangible"
    baseVocab: "http://schema.org/"
    subClassOf:
      - "Thing"

  Class:
    path: "Thing/Intangible/Class"
    baseVocab: "http://schema.org/"
    subClassOf:
      - "Intangible"
    properties:
      - "supersededBy"

  Property:
    path: "Thing/Intangible/Property"
    baseVocab: "http://schema.org/"
    subClassOf:
      - "Intangible"
    properties:
      - "rangeIncludes"
      - "domainIncludes"
      - "supersededBy"
      - "inverseOf"

  Enumeration:
    path: "Thing/Intangible/Enumeration"
    baseVocab: "http://schema.org/"
    subClassOf:
      - "Intangible"
    properties:
      - "supersededBy"

  ItemList:
    path: "Thing/Intangible/ItemList"
    baseVocab: "http://schema.org/"
    subClassOf:
      - "Intangible"
    properties: []

  EntryPoint:
    path: "Thing/Intangible/EntryPoint"
    baseVocab: "http://schema.org/"
    comment: ""
    subClassOf:
      - "Intangible"
    properties: []

  DataType:
    comment: ""
    path: "Thing/Intangible/Class/DataType"
    baseVocab: "http://schema.org/"
    subClassOf:
      - "Class"
      - "rdfs:datatype"

  Person:
    comment: ""
    path: "Thing/Person"
    baseVocab: "http://schema.org/"
    subClassOf:
      - "Thing"
    properties: []

  Organization:
    comment: ""
    path: "Thing/Organization"
    baseVocab: "http://schema.org/"
    subClassOf:
      - "Thing"
    properties: []

  Place:
    comment: ""
    path: "Thing/Place"
    baseVocab: "http://schema.org/"
    subClassOf:
      - "Thing"
    properties: []

  StructuredValue:
    comment: ""
    path: "Thing/Intangible/StructuredValue"
    baseVocab: "http://schema.org/"
    subClassOf:
      - "Intangible"
    properties: []

  ContactPoint:
    comment: ""
    path: "Thing/Intangible/StructuredValue/ContactPoint"
    baseVocab: "http://schema.org/"
    subClassOf:
      - "StructuredValue"
    properties: []

  CreativeWork:
    comment: ""
    path: "Thing/CreativeWork"
    baseVocab: "http://schema.org/"
    subClassOf:
      - "Thing"
    properties: []

  MediaObject:
    comment: ""
    path: "Thing/CreativeWork/MediaObject"
    baseVocab: "http://schema.org/"
    subClassOf:
      - "CreativeWork"
    properties: []

  ImageObject:
    comment: ""
    path: "Thing/CreativeWork/MediaObject/ImageObject"
    baseVocab: "http://schema.org/"
    subClassOf:
      - "MediaObject"
      - "http://schema.org/ImageObject"
    properties: []

  Action:
    comment: ""
    subClassOf:
      - "Thing"
      - "http://schema.org/Action"
    properties:
      - "actionStatus"
      - "agent"
      - "error"
      - "instrument"
      - "location"
      - "startTime"
      - "endTime"
      - "object"
      - "participant"
      - "result"
      - "target"

  ActionStatusType:
    comment: ""
    subClassOf:
      - "Enumeration"
      - "http://schema.org/ActionStatusType"

  Boolean:
    comment: ""
    path: "DataType/Boolean"
    subClassOf:
      - "DataType"
      - "http://schema.org/Boolean"

  Date:
    path: "DataType/Date"
    subClassOf:
      - "DataType"
      - "http://schema.org/Date"

  DateTime:
    path: "DataType/DateTime"
    subClassOf:
      - "DataType"
      - "http://schema.org/DateTime"

  Integer:
    path: "DataType/Integer"
    subClassOf:
      - "Number"
      - "http://schema.org/Integer"

  Number:
    path: "DataType/Number"
    subClassOf:
      - "DataType"
      - "https://schema.org/Number"

  Text:
    path: "DataType/Text"
    subClassOf:
      - "DataType"
      - "https://schema.org/Text"

  Time:
    path: "DataType/Time"
    subClassOf:
      - "DataType"
      - "https://schema.org/Time"

  URL:
    path: "DataType/Text/URL"
    subClassOf:
      - "Text"
      - "https://schema.org/URL"

  Yes:
    subClassOf:
      - "Boolean"

  No:
    subClassOf:
      - "Boolean"

  True:
    subClassOf:
      - "Boolean"

  False:
    subClassOf:
      - "Boolean"

# All properties have the RDF type of rdfs:Property and http://oerschema.org/Property
properties:
  name:
    comment: "The name of the item."
    range:
      - "Text"
    domain:
      - "Thing"
      - "http://schema.org/Thing"

  additionalName:
    comment: "An alias for the item."
    range:
      - "Text"
    domain:
      - "Thing"
      - "http://schema.org/Thing"

  additionalType:
    comment: "An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax."
    range:
      - "Class"
    domain:
      - "Thing"
      - "http://schema.org/Thing"

  description:
    comment: "A short description of the item."
    range:
      - "Text"
    domain:
      - "Thing"
      - "http://schema.org/Thing"

  image:
    comment: "An image of the item."
    range:
      - "URL"
      - "CreativeWork"
    domain:
      - "Thing"
      - "http://schema.org/Thing"

  mainEntityOfPage:
    comment: ""
    range:
      - "URL"
      - "CreativeWork"
    domain:
      - "Thing"
      - "http://schema.org/Thing"

  sameAs:
    comment: ""
    range:
      - "URL"
    domain:
      - "Thing"
      - "http://schema.org/Thing"

  url:
    comment: ""
    range:
      - "URL"
    domain:
      - "Thing"
      - "http://schema.org/Thing"

  potentialAction:
    comment: ""
    range:
      - "Action"
    domain:
      - "Thing"
      - "http://schema.org/Thing"

  actionStatus:
    comment: ""
    range:
      - "ActionStatusType"
    domain:
      - "Action"
      - "http://schema.org/Action"

  agent:
    comment: ""
    range:
      - "Organization"
      - "Person"
    domain:
      - "Action"
      - "http://schema.org/Action"

  endTime:
    comment: ""
    range:
      - "DateTime"
    domain:
      - "Action"
      - "http://schema.org/Action"

  startTime:
    comment: ""
    range:
      - "DateTime"
    domain:
      - "http://schema.org/Action"

  object:
    comment: ""
    range:
      - "Thing"
    domain:
      - "Action"
      - "http://schema.org/Action"

  result:
    comment: ""
    range:
      - "Thing"
    domain:
      - "Action"
      - "http://schema.org/Action"

  error:
    comment: ""
    range:
      - "Thing"
    domain:
      - "Action"
      - "http://schema.org/Action"

  instrument:
    comment: ""
    range:
      - "Thing"
    domain:
      - "Action"
      - "http://schema.org/Action"

  location:
    comment: ""
    range:
      - "Place"
      - "PostalAddress"
      - "Text"
    domain:
      - "Action"
      - "http://schema.org/Action"

  participant:
    comment: ""
    range:
      - "Organization"
      - "Person"
    domain:
      - "Action"
      - "http://schema.org/Action"

  result:
    comment: ""
    range:
      - "Thing"
    domain:
      - "Action"
      - "http://schema.org/Action"

  rangeIncludes:
    comment: "Relates a property to a class that constitutes (one of) the expected type(s) for values of the property."
    range:
      - "Class"
    domain:
      - "Thing"
      - "http://schema.org/Thing"

  domainIncludes:
    comment: "Relates a property to a class that is (one of) the type(s) the property is expected to be used on."
    range:
      - "Class"
    domain:
      - "Property"
      - "http://schema.org/Property"

  supersededBy:
    comment: ""
    range:
      - "Class"
      - "Property"
      - "Enumeration"
    domain:
      - "Class"
      - "Property"
      - "Enumeration"
      - "http://schema.org/Class"
      - "http://schema.org/Property"
      - "http://schema.org/Enumeration"

  inverseOf:
    comment: "Relates a property to a property that is its inverse. Inverse properties relate the same pairs of items to each other, but in reversed direction. For example, the 'alumni' and 'alumniOf' properties are inverseOf each other. Some properties don't have explicit inverses; in these situations RDFa and JSON-LD syntax for reverse properties can be used."
    range:
      - "Property"
    domain:
      - "Property"
      - "http://schema.org/Property"