name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Change this to your default branch if it's not 'main'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Updated to v3
      with:
        node-version: '20'  # Use Node.js 18

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm build  # Adjust this command to your build script

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # Adjust this to your build output directory